// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXgUNsffUSJErnlzQwoVyBwtk4BzJ3K4',
    appId: '1:465111730158:web:c4e43d7fee4bbc5437b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    authDomain: 'convenient-way.firebaseapp.com',
    storageBucket: 'convenient-way.appspot.com',
    measurementId: 'G-N3GS2FDY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXy653QraMBHtNQcsRTn3Ac9V6xqj_SsQ',
    appId: '1:465111730158:android:363b7c6f3630613137b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    storageBucket: 'convenient-way.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWgBJ_4hWesEzmuzPt9h5-b6epxng4jY',
    appId: '1:465111730158:ios:d1e992569ac8785537b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    storageBucket: 'convenient-way.appspot.com',
    iosClientId: '465111730158-0tf90l46h8mgusiskgv8lraiit5idv73.apps.googleusercontent.com',
    iosBundleId: 'com.example.convenientWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWgBJ_4hWesEzmuzPt9h5-b6epxng4jY',
    appId: '1:465111730158:ios:d1e992569ac8785537b0ff',
    messagingSenderId: '465111730158',
    projectId: 'convenient-way',
    storageBucket: 'convenient-way.appspot.com',
    iosClientId: '465111730158-0tf90l46h8mgusiskgv8lraiit5idv73.apps.googleusercontent.com',
    iosBundleId: 'com.example.convenientWay',
  );
}
